baseURL = "https://gochaos-app.github.io/"
theme="hugo-theme-learn"
languageCode = "en-us"
title = "Go-Chaos"

[params]
themeVariant = "green"
showVisitedLinks = true

[outputs]
home = ["HTML","RSS","JSON"]

[Clear-History]
other = "Clear History"

